#pragma once


#define	PASSWORD_FAILED					 0
#define PASSWORD_SUCCESS				 1 

#define PASSWORD_INPUT_SUCCESS			 3
#define	PASSWORD_INPUT_FAILED			-3 
#define	PASSWORD_OPEN_FILE_FAILED		-4 

#define PASSWORD_READ_FILE_SUCCESS		 5 
#define	PASSWORD_READ_FILE_FAILED		-5 
#define	PASSWORD_WRITE_FILE_SUCCESS		 6 
#define	PASSWORD_WRITE_FILE_FAILED		-6 
#define	PASSWORD_RESET_SUCCESS			 7 
#define	PASSWORD_RESET_FAILED			-7 
#define	PASSWORD_MATCH_SUCCESS			 8 
#define	PASSWORD_MATCH_FAILED			-8
#define PASSWORD_LANDING_SUCCESS		 9
#define PASSWORD_LANDING_FAILED			-9



#define	 PASSWORD_INPUT_NEW_PASSWORD		 10
#define	 PASSWORD_INPUT_OLD_PASSWORD		 11
#define	 PASSWORD_INPUT_NEW_PASSWORD_AGAIN	 12 
#define  PASSWORD_INPUT_PASSWORD			 13

//menu
#define  PASSWORD_RESET								1
#define  PASSWORD_LANDING							2
#define  PASSWORD_LOG_OUT							3